a = {
    "openai_api_key": "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",
    "openai_model": "gpt-4o-mini",
    "openai_temperature": 0.3,
    "strands_model_provider": "openai",
    "strands_max_retries": 3,
    "strands_timeout": 120,
    "default_output_dir": "specs",
    "git_branch_prefix": "specgen/scenario-3",
    "git_commit_prefix": "spec",
    "incremental_save": True,
    "min_improvement_threshold": 5.0,
    "parallel_processing": True,
    "early_stopping": True,
    "show_progress": True,
    "enable_token_optimization": True,
    "max_openapi_size": 15000,
    "use_minimal_templates": True,
    "quality_threshold": 70.0,
    "consistency_threshold": 75.0,
    "max_iterations": 3,
}
